version: '2'

networks:
  default:
    driver: bridge

services:
  eureka:
    build: ../JAlgoArena-Eureka
    image: eureka:tag
    container_name: jalgoarena_eureka
    ports:
      - 5000:5000

  ui:
    container_name: jalgoarena_ui
    build: ../JAlgoArena-UI
    image: ui:tag
    depends_on:
      - eureka
    ports:
      - 3000:3000

  api:
    container_name: jalgoarena_api
    build: ../JAlgoArena-API
    image: api:tag
    depends_on:
      - eureka
    ports:
      - 5001:5001

  auth:
    container_name: jalgoarena_auth
    build: ../JAlgoArena-Auth
    image: auth:tag
    depends_on:
      - eureka
    ports:
      - 9999:9999

  judge:
    container_name: jalgoarena_judge
    build: ../JAlgoArena-Judge
    image: judge:tag
    depends_on:
      - eureka
    ports:
      - 8080:8080

  problems:
    container_name: jalgoarena_problems
    build: ../JAlgoArena-Problems
    image: problems:tag
    depends_on:
      - eureka
    ports:
      - 5002:5002

  submissions:
    container_name: jalgoarena_submissions
    build: ../JAlgoArena-Submissions
    image: submissions:tag
    depends_on:
      - eureka
    ports:
      - 5003:5003
